### ISSUE TITLE
Support seatd

### ISSUE THREAD

**Issue by crocket** [swaywm/swayidle#100]
sway and wlroots support seatd. seatd support in swayidle would increase consistency across sway platform.

**Comment by emersion** [comment]
I don't think it makes sense, because seatd doesn't manage sleep/locking, for good reasons.

**Comment by crocket** [comment]
Does it mean swayidle is going to keep needing elogind for non-root sway sessions?

**Comment by emersion** [comment]
swayidle doesn't need logind.
