### ISSUE TITLE
Additional option for the lid switch of laptops

### ISSUE THREAD

**Issue by Kilobyte22** [swaywm/swayidle#103]
I propose two additional options `lid-close` and `lid-open`, which are triggered when the lid of a laptop is closed. A good example of a usecase would be to start a lock screen, even when a device is not configured to go to sleep when when it is closed. You could also start a timer to lift an inhibitor, and cancel said timer in the `lid-open` callback, allowing to delay suspend after closing the lid.

**Comment by emersion** [comment]
swayidle doesn't have access to lid events. Instead, your compositor (e.g. Sway) can be configured to run a command on lid switch events.
