### ISSUE TITLE
Swayidle kicks in despite video playing

### ISSUE THREAD

**Issue by mastertinner** [swaywm/swayidle#104]
Currently, for me, `swayidle` seems to lock the screen even if a video is playing in my browser or if I'm in a video call and just don't touch any input devices.

Is there a way to make it respect these cases and not trigger as long as a video is being played in the foreground?

Here's my Sway config: https://github.com/mastertinner/dotfiles/blob/main/sway/.config/sway/config#L26

As a browser, I'm using Brave: `brave --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by GreyXor** [comment]
Your config is good and you don't have to do anything more.
Everything is automatically handled by [idle-inhibit](https://gitlab.freedesktop.org/wayland/wayland-protocols/tree/master/unstable/idle-inhibit). If it doesn't work, it's `Brave` or `Chromium` fault.

You can try with Firefox for example, it manages the idle-inhibit.

**Comment by mastertinner** [comment]
Thanks, @GreyXor! I'm using the latest Brave/Chromium. But I guess that means the bug is with Chromium.
