### ISSUE TITLE
Swayidle blocks screen while playing games with a controller.

### ISSUE THREAD

**Issue by gbj1viciado** [swaywm/swayidle#110]
Swayidle doesn't seem to identify joysticks inputs as a activity on the system, putting it to sleep, this doesn't happen if playing games using keyboard.

**Comment by emersion** [comment]
Yes. Sway manages this, and doesn't open gamepad devices at all.

**Comment by ammgws** [comment]
@gbj1viciado Did you come up with a solution for the time being?

**Comment by gbj1viciado** [comment]
@ammgws Yes actually at least  on sway. 
for_window [shell=".*"] inhibit_idle fullscreen
will make it so swayidle doesn't block the screen if a full screen app is active. It will still block the screen if you play a game on window mode. for that i used sway-audio-idle-inhibit make it so it won't block the screen if audio is playing.
You can find sway-audio-idle-inhibit here. https://github.com/ErikReider/SwayAudioIdleInhibit

**Comment by jason-shen** [comment]
> 

this no longer works
