### ISSUE TITLE
use pulsaudio / pipewire processes for media inhibition

### ISSUE THREAD

**Issue by asklow** [swaywm/swayidle#134]
Not yet switched from i3 to sway. Am looking for a way similar to `xidlehook's `  [`--not-when-audio`](https://gitlab.com/jD91mZM2/xidlehook#example) solution, instead of relying on some different obscure inhibition techniques.
This way works on all kinds of media playbacks on all applications like players, browsers, etc.

**Comment by kennylevinsen** [comment]
Same answer as for https://github.com/swaywm/swayidle/issues/37#issuecomment-1306541430

Wayland clients can inhibit idle using [the idle inhibition protocol](https://wayland.app/protocols/idle-inhibit-unstable-v1). That's what your video player or browser is supposed to do.

swayidle does not decide when the system is idle, but merely runs command when it is told the system has been idle for the specified period of time through [the idle protocol](https://wayland.app/protocols/ext-idle-notify-v1).
