### ISSUE TITLE
Idle timer is not reset on touchscreen input

### ISSUE THREAD

**Issue by Smona** [swaywm/swayidle#135]
I'm using swayidle on a 2-in-1 laptop, so occasionally I won't be using a mouse or keyboard. For the most part swayidle works really well, but unfortunately it breaks this use case for me, since my screen will blank no matter how much I'm touching the screen. This is surprising to me, since the mouse cursor is moving during this touch input.

I'm very new to the whole wlroots stack so let me know if this would best be filed elsewhere, but it looked like swayidle should be handling this. For what it's worth, I'm using hyprland v17.

**Comment by emersion** [comment]
This is a compositor bug. swayidle is notified when the user is idle by the compositor.

Please report this to the Hyprland issue tracker.
