### ISSUE TITLE
No inhibit when moving mouse over empty desktop

### ISSUE THREAD

**Issue by Lassebq** [swaywm/swayidle#145]
Swayidle seems to only inhibit when moving mouse over clients (windows), can anyone else confirm this?

**Comment by FriederHannenheim** [comment]
This is likely not a swayidle issue but an issue with your compositor. Swayidle uses the ext-idle-notify wayland protocol and relies on the compositor to tell if the user is idle or not

**Comment by kennylevinsen** [comment]
Note that inhibition refers to when idle behavior is disabled altogether by an application such as a video player. Typing or moving the cursor is just activity that resets idle time.

To _automatically_ inhibit idle during e.g. a video, both your compositor and the application need to support and use the idle-inhibit protocol. In sway you can optionally configure manual inhibition when the application does not do it by itself, see `man 5 sway`, `inhibit_idle`.

**Comment by Lassebq** [comment]
It seems that it doesn't happen anymore, but I'm pretty sure it used to happen with Hyprland at least. Not too sure if river had the same issue.

**Comment by Lassebq** [comment]
Considering it doesn't happen anymore, I can close the issue
