### ISSUE TITLE
An idle that ignores inhibit_idle and only cares about keyboard/mouse input

### ISSUE THREAD

**Issue by Kommynct** [swaywm/swayidle#158]
I want to make it so that my computer displays a note if i haven't been at it in a certain amount of time, but I want things that inhibit_idle in my sway config not to affect that, and only the keyboard/mouse to be relevant.

Is there a good way to do that? I don't see anything in the man pages that would help me.

**Comment by kennylevinsen** [comment]
No, swayidle only knows about idle when sway informs it that an idle timer expired, and those are affected by inhibition.

Swayidle cannot see system activity on its own.
