### ISSUE TITLE
[Help] Using with swaylock, different timeout when swaylock is activated

### ISSUE THREAD

**Issue by omnigenous** [swaywm/swayidle#159]
```sh
swayidle -w timeout 300 "swaylock -f" timeout 360 "hyprctl dispatch dpms off" resume "hyprctl dispatch dpms on"
```
Sometimes I just touch my mouse by accident when my screen is off (from swayidle) and then I would need to wait 360 seconds for my screen to turn off, other times I would go afk and manually use swaylock and then my screen would turn after same 360 seconds.

I want my screen to turn off after 60 seconds if my screen is already locked with swaylock, is this possible or is this another instance of #97 ?

**Comment by kennylevinsen** [comment]
This is not possible with swayidle, which monitors activity. By definition, there is activity when the mouse is moved, and so all timeouts resume and start at 0.

For these kinds of things, it might be better to have a lockscreen that can turn screens off with its own logic. E.g., "immediately off when launched", "quickly off on just mouse movement or single keypress", "stay on for longer if typed on".

**Comment by omnigenous** [comment]
> By definition, there is activity when the mouse is moved, and so all timeouts resume and start at 0.

I get that, but after timer resets to 0 I would prefer if swayidle turnoff my screen after 60 seconds instead of regular 360 I set if my system is locked with swaylock. Am I not understanding something?

**Comment by kennylevinsen** [comment]
Swayidle timeouts can only be set when it starts, so this would require you to kill the current swayidle and start a new one whenever you want the timeout to change.

This is why I said it might be better to have the lockscreen contain the logic you want, as that would know what is going on while swayidle only knows if its timeouts have expired.

**Comment by omnigenous** [comment]
Thank you for clarifying! On the side note, do you have any specific lockscreen software recommendations I could use?

**Comment by laktak** [comment]
I think you can do this when you add an early timeout that checks and only activates when swaylock is running, e.g.

```
    swayidle -w -d \
      timeout 30 'pgrep swaylock && swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
      ... # normal timeout options
```
