### ISSUE TITLE
configuration change

### ISSUE THREAD

**Issue by mdeff** [swaywm/swayidle#22]
Is it possible (or can it be made possible) to change `swayidle` config after launching it?

My use case would be to run
```
swayidle -w \
    timeout 600 'swaymsg "output * dpms off"' \
         resume 'swaymsg "output * dpms on"' \
```
in most situations, but disable DPMS on idle when I'm watching TV or presenting on a beamer (I have a key combination to configure my outputs in this mode). For now I'm running `pkill swayidle`, but that doesn't seem right.

**Comment by emersion** [comment]
>disable DPMS on idle when I'm watching TV or presenting on a beamer

Apps you use should use the idle-inhibit protocol.

Related to https://github.com/swaywm/sway/issues/2595

**Comment by mdeff** [comment]
Good to know! That would solve my problem indeed. I guess Firefox doesn't handle it yet... (My presentation app is [pdfpc](https://pdfpc.github.io), I don't know if they implemented it). Inhibiting with a criteria (swaywm/sway#3070) would also be useful.

Either way, I still think it would be great to be able to reconfigure `swayidle` on the fly. Feel free to close if you don't think so.
