### ISSUE TITLE
RFE: Ability to temporarily disable timeouts

### ISSUE THREAD

**Issue by zeroxfourc** [swaywm/swayidle#31]
Right now there is no easy way to temporarily disable swayidle's timeouts, short of killing it and restarting it later. I'd like there to be a way to tell swayidle to stop and restart timeouts, perhaps via signals, like SIGUSR1 makes it enter idle mode.

**Comment by boucman** [comment]
I had implemented a PR to do that, but that's not the proper way to do it.

It's the compositor's job to tell swayidle to pause. The next (latest?) version of sway does that, and you can disable idleness via your sway configuration.

**Comment by zeroxfourc** [comment]
Right, thank you for your reply. Closing this.
