### ISSUE TITLE
locks away while watching movie ??

### ISSUE THREAD

**Issue by sk0x1234** [swaywm/swayidle#37]
im using mpv to watch a movie, suddenly it activates swaylock !! ?

**Comment by ReekyMarko** [comment]
@sk0x1234 You will need to either kill swayidle or inhibit it. I'm using waybar and it's [idle inhibitor](https://github.com/Alexays/Waybar/wiki/Module:-Idle-Inhibitor)

**Comment by 3nuc** [comment]
Heads up that idle inhibitor is just an on/off switch that you have to activate manually before watching a movie/starting a presentation. It's not a magic automatic inhibitor thing that inhibits swaylock if you're watching a movie

**Comment by kennylevinsen** [comment]
Wayland clients can inhibit idle using [the idle inhibition protocol](https://wayland.app/protocols/idle-inhibit-unstable-v1). That's what your video player or browser is supposed to do.

swayidle does not decide when the system is idle, but merely runs command when it is told the system has been idle for the specified period of time through [the idle protocol](https://wayland.app/protocols/ext-idle-notify-v1).
