### ISSUE TITLE
systemd/logind IdleAction taken despite not being idle

### ISSUE THREAD

**Issue by carloabelli** [swaywm/swayidle#4]
I am trying to enable auto suspend through systemd/logind. In `/etc/systemd/logind.conf` I have the lines:
```
IdleAction=suspend
IdleActionSec=1min
```

However this causes my system to suspend every 1 minute regardless of activity or inactivity. My guess was that sway is not correctly reporting its idle state based on https://github.com/systemd/systemd/issues/1295.

**Comment by emersion** [comment]
swayidle now listens to the `Lock`/`Unlock` signals: https://github.com/swaywm/swayidle/pull/24

**Comment by Tormen** [comment]
I just ran into the same problem:
When changing `IdleAction` from the default `ignore` to `suspend` within `/etc/systemd/logind.conf` then the laptop even though during keybaord-usage and mouse-usage suspends every `IdleActionSec`.

**Comment by tmccombs** [comment]
Is there a reason not to have swayidle (with logind support) support setting the IdleHint for the session?

**Comment by emersion** [comment]
No

**Comment by edrex** [comment]
This doesn't seem to work for me.
I have `idlehint 120` in my swayidle command, but logind still suspends every `IdleActionSec`. 

Digging in, I don't see an inhibit from swayidle:

```
❯ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1 -m org.freedesktop.login1.Manager.ListInhibitors
([('sleep', 'electron', 'Application cleanup before suspend', 'delay', uint32 1000, uint32 13258), ('sleep', 'NetworkManager', 'NetworkManager needs to turn off networks', 'delay', 0, 653), ('sleep', 'UPower', 'Pause device polling', 'delay', 0, 8951)],)
```

@electrickite is this the right way to configure?

**Comment by electrickite** [comment]
@edrex The `idlehint` event will cause swayidle to set the logind IdleHint to True after `<seconds>` of inactivity. When activity resumes, it will set IdleHint to false.

So `idlehint 120` will set IdleHint true after the user is idle for 120 seconds. Logind should then execute its IdleAction after an additional IdleActionSec as configured in logind.conf.

I noticed that IdleHint was only correctly set if swayidle was executed from the sway config using an exec command: it was not able to connect to the D-Bus session if run from the terminal of a logged in session.

**Comment by edrex** [comment]
I see debug message `SetIdleHint 0` but the value on the bus is still `True`.

The issue seems to be that the `SetIdleHint` calls are being ignored:

```
❯ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/auto -m org.freedesktop.login1.Session.SetIdleHint false                           
()
                                                                                                                                                                                 
~   
❯ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/auto -m org.freedesktop.DBus.Properties.Get org.freedesktop.login1.Session IdleHint
(<true>,)
```
> I noticed that IdleHint was only correctly set if swayidle was executed from the sway config using an exec command: it was not able to connect to the D-Bus session if run from the terminal of a logged in session.

This is interesting. Does logind ignore `SetIdleHint` if not called by the session `pid`? Anyway, swayidle launched from sway config `exec` doesn't help for me.

Any process can set an inhibit lock. Should swayidle be using this mechanism instead?

**Comment by electrickite** [comment]
> Any process can set an inhibit lock. Should swayidle be using this mechanism instead?

The goal of this feature (or at least the PR) is to correctly set the session IdleHint. I would prefer not to use inhibitor locks - they are semantically distinct from the session idle state. 

It seems as though SetIdleHint is not being set at all on your system? i.e. even manually calling it via gdbus does not work?

**Comment by edrex** [comment]
> The goal of this feature (or at least the PR) is to correctly set the session IdleHint. I would prefer not to use inhibitor locks - they are semantically distinct from the session idle state.

Ok, I understand

> It seems as though SetIdleHint is not being set at all on your system? i.e. even manually calling it via gdbus does not work?

Looks to be. I'm on arch. Does the above work for you?

Logind only checks that the calling process is owned by the session owner:

https://github.com/systemd/systemd/blob/a859abf062cef1511e4879c4ee39c6036ebeaec8/src/login/logind-session-dbus.c#L249

Useful reference: https://www.freedesktop.org/wiki/Software/systemd/writing-desktop-environments/

**Comment by edrex** [comment]
To verify that the call is getting to logind, tried setting idlehint as another user:
```
fuser❯ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/_31 -m org.freedesktop.login1.Session.SetIdleHint false
Error: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Only owner of session may set idle hint
```

**Comment by tmccombs** [comment]
> gdbus monitor -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/auto doesn't report any property changes, so it's evidently not some other caller immediately setting it back to true.

I don't believe the auto session emits events for idle hint changes. At least from my experiments, I didn't see property change evnts when monitoring the auto session object, but I did if I monitored the actual session object with the session name. (Also on arch)

**Comment by tmccombs** [comment]
> I noticed that IdleHint was only correctly set if swayidle was executed from the sway config using an exec command: it was not able to connect to the D-Bus session if run from the terminal of a logged in session.

Why would that be? Afaik, logind wouldn't be able to tell if it was started from an exec in config or not.

**Comment by electrickite** [comment]
@edrex FWIW, I just verified that I am able to set the IdleHint for the session from the terminal. (Arch, sway, no display manager). Note that these commands use the session path, as @tmccombs suggests.

    $ dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.ListSessions
    method return time=1574128317.662196 sender=:1.8 -> destination=:1.104 serial=70 reply_serial=2
       array [
          struct {
             string "1"
             uint32 1100
             string "corey"
             string "seat0"
             object path "/org/freedesktop/login1/session/_31"
          }
       ]
    $ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/_31 -m org.freedesktop.DBus.Properties.Get org.freedesktop.login1.Session IdleHint
    (<false>,)
    $ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/_31 -m org.freedesktop.login1.Session.SetIdleHint true
    ()
    $ gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1/session/_31 -m org.freedesktop.DBus.Properties.Get org.freedesktop.login1.Session IdleHint
    (<true>,)

**Comment by electrickite** [comment]
@tmccombs I did a little digging into why swayidle could only set the IdleHint when run from `exec` in sway config. Turns out it was a different issue: I was running swayidle from bash under the GNOME Terminal emulator. `gnome-terminal-server` is started as a systemd user service, which are not associated with a particular session. So any child process also lacks a session, meaning that swayidle cannot determine the correct session from its PID.

When run from swaymsg, swayidle is executed within the session context.

**Comment by edrex** [comment]
> I don't believe the auto session emits events for idle hint changes.

Same using explicit session (`_31` for me)

> I just verified that I am able to set the IdleHint for the session from the terminal.

@electrickite what about setting back to `false`? The behavior I'm seeing is the props (`IdleHint` and `LockedHint`) are stuck `true`.

Anyway it doesn't look to be specific to swayidle so I sent it upstream.

**Comment by edrex** [comment]
https://github.com/systemd/systemd/issues/14053#issuecomment-571274895:
> currently you can mark a tty session idle, but never unmark it

This feature will not work properly under a TTY session. Perhaps the time has come for a wlroots display manager https://github.com/swaywm/wlroots/issues/540#issuecomment-571295975

**Comment by emersion** [comment]
Isn't this a systemd bug?

**Comment by boucman** [comment]
this is currently be discussed on the systemd side too, see https://github.com/systemd/systemd/issues/14489

**Comment by tmccombs** [comment]
> Isn't this a systemd bug?

Kind of. My understanding is it is expected (but not ideal) behaviour, because Logind doesn't expect a console session to change into a graphical session.

**Comment by electrickite** [comment]
A PR was merged into systemd today that should land in v246. It adds a SetType method to the logind dbus interface. This will at least allow systemd to support a session type upgrade, although the compositor will still need to implement the switch.

**Comment by zlandau** [comment]
Thanks for your work in pushing that through, @electrickite!
