### ISSUE TITLE
Prematurely Trigger Idle

### ISSUE THREAD

**Issue by JonathanILevi** [swaywm/swayidle#43]
Is it possible to execute a command to prematurely trigger an idle?  I have have swayidle putting my turning my screens off after a delay but I would like to be able to manually trigger it.  If not could it be possible to just specify a command to execute on the next activity?

**Comment by RedSoxFan** [comment]
Send `SIGUSR1` to swayidle

**Comment by JonathanILevi** [comment]
Um, how do I do that?

**Comment by RedSoxFan** [comment]
`killall -SIGUSR1 swayidle` or `pkill -SIGUSR1 swayidle`
