### ISSUE TITLE
DPMS event

### ISSUE THREAD

**Issue by abelfodil** [swaywm/swayidle#44]
When using 

 `swayidle -w
                timeout 300 'swaylock -f -c 000000'
                timeout 600 'swaymsg "output * dpms off"'
                     resume 'swaymsg "output * dpms on"'
                before-sleep 'swaylock -f -c 000000'` 

while watching a long video, the screen is locked. Is there a way to listen to a DPMS event (like `xss-lock` does) instead in Wayland?

**Comment by emersion** [comment]
Your video player needs to implement the idle-inhibit Wayland protocol.
