### ISSUE TITLE
Support org.freedesktop.portal.Inhibit D-Bus interface

### ISSUE THREAD

**Issue by eternal-sorrow** [swaywm/swayidle#46]
It is used by flatpak apps (xdg-desktop-portal). Also, GTK developers refused to support `idle-inhibit`  wayland protocol and recommend using D-Bus interfaces instead. https://gitlab.gnome.org/GNOME/gtk/issues/2202

**Comment by emersion** [comment]
Thanks for linking this issue. I really think GTK should implement the Wayland protocol, which is superior.

**Comment by ddevault** [comment]
Aye, I agree that this is not how this feature should be implemented.

**Comment by eternal-sorrow** [comment]
@ddevault Does it mean that D-Bus interface shouldn't be implemented?

**Comment by ddevault** [comment]
Yes.
