### ISSUE TITLE
How to stop swayidle when playing movie with mpv player?

### ISSUE THREAD

**Issue by alvin998179** [swaywm/swayidle#65]
How to stop swayidle when playing movie with mpv player?  I use arch linux with sway wm .

**Comment by martinetd** [comment]
mpv implements `idle-inhibit-unstable-v1`, you're either out of date or not using the wayland backend (`--gpu-context=wayland` last time I checked) it should just work.

**Comment by alvin998179** [comment]
Thank you !

**Comment by alvin998179** [comment]
But I can not use "--gpu-context=wayland" to play movie, as there is not video optput. Could you please tell me how to use the wayland backend in mpv ?

**Comment by martinetd** [comment]
It works here on mpv `0.30.0-297-gad2cda343b`. This isn't the place to discuss user problems, please ask on `#sway` (or your compositor's channel), or `#mpv`, on irc.freenode.net for more interactive discussions

**Comment by alvin998179** [comment]
Thanks you !
